name: 'Yuki-no'
description: 'Automatic git commit tracking service.'

inputs:
  access-token:
    description: 'GitHub access token.'
    required: true
  username:
    description: 'Git username used for GitHub issue operations. Defaults to "github-actions".'
    required: false
    default: 'github-actions'
  email:
    description: 'Git username used for GitHub issue operations. Defaults to "action@github.com".'
    required: false
    default: 'action@github.com'
  upstream-repo:
    description: 'URL of your repository. If not specified, the current working repository will be used. e.g. https://github.com/vitejs/docs-ko.git'
    required: false
  head-repo:
    description: 'URL of repository to track. e.g. https://github.com/vitejs/vite.git'
    required: true
  head-repo-branch:
    description: 'Branch to track in head repo. Defaults to "main".'
    required: false
    default: 'main'
  track-from:
    description: 'Starting commit hash. Tracking starts from the next commit.'
    required: true
  include:
    description: 'Glob patterns for files to track. If not specified, all files will be tracked.'
    required: false
  exclude:
    description: 'Glob patterns for files to exclude. Take precedence over include patterns.'
    required: false
  plugins:
    description: 'Names of Yuki-no plugins to load with exact version specification (newline separated). Format: plugin-name@1.0.0 (exact version required).'
    required: false
  labels:
    description: 'Labels for issues. You can specify multiple labels separated by newlines. If empty string is provided, no labels will be added. Defaults to "sync".'
    required: false
    default: |
      sync
  release-tracking:
    description: '(Deprecated) Whether to enable release tracking. Use plugins: ["core:release-tracking"] instead.'
    required: false
    deprecationMessage: 'release-tracking option is deprecated. Use plugins: ["core:release-tracking"] instead. See documentation for migration guide.'
  release-tracking-labels:
    description: '(Deprecated) Labels for unreleased changes. Use env.RELEASE_TRACKING_LABELS instead.'
    required: false
    deprecationMessage: 'release-tracking-labels option is deprecated. Set RELEASE_TRACKING_LABELS in env block instead.'
    default: |
      pending
  verbose:
    description: 'When enabled, Yuki-no will show all log messages including info and success messages. This is useful for debugging.'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "YUKI_NO_VERSION=${action_ref}" >> $GITHUB_ENV

        echo "PLUGINS<<EOF" >> $GITHUB_ENV
        echo "${plugins}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        action_ref: ${{ github.action_ref }}
        plugins: ${{ inputs.plugins }}

    - name: Checkout Yuki-no
      run: ${{ github.action_path }}/scripts/checkout.sh
      shell: bash

    - name: Run Yuki-no
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        USER_NAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        UPSTREAM_REPO: ${{ inputs.upstream-repo }}
        HEAD_REPO: ${{ inputs.head-repo }}
        HEAD_REPO_BRANCH: ${{ inputs.head-repo-branch }}
        TRACK_FROM: ${{ inputs.track-from }}
        INCLUDE: ${{ inputs.include }}
        EXCLUDE: ${{ inputs.exclude }}
        PLUGINS: ${{ inputs.plugins }}
        LABELS: ${{ inputs.labels }}
        RELEASE_TRACKING: ${{ inputs.release-tracking }}
        RELEASE_TRACKING_LABELS: ${{ inputs.release-tracking-labels }}
        VERBOSE: ${{ inputs.verbose }}
      run: |
        cd yuki-no
        yarn start
      shell: bash
