name: 'Ryu-Cho'
description: 'Automatic git commit tracking service.'

inputs:
  access-token:
    description: 'GitHub access token.'
    required: true
  username:
    description: 'Git user name to use when making issues and PRs. Defaults to "github-actions". Note: Using only one of username or email might cause GitHub Actions bot to work incorrectly.'
    required: false
    default: 'github-actions'
  email:
    description: 'Git email address to use when making issues and PRs. Defaults to "action@github.com". Note: Using only one of username or email might cause GitHub Actions bot to work incorrectly.'
    required: false
    default: 'action@github.com'
  upstream-repo:
    description: 'The url for the upstream repo. This is the repository that you set up Ryu-Cho. e.g. https://github.com/vitejs/docs-ko.git'
    required: true
  head-repo:
    description: 'The head repo to track. This is the repository you want to take a diff. e.g. https://github.com/vitejs/vite.git'
    required: true
  head-repo-branch:
    description: 'The branch for the head repo. Defaults to "main".'
    required: false
    default: 'main'
  track-from:
    description: 'The git commit sha of head repo to start tracking. Ryu-Cho will only track commit from this hash.'
    required: true
  path-starts-with:
    description: 'File path to track. If specified, Ryu-Cho will only track commits that modified files under this path. If not specified, it will track all files in the project root.'
    required: false
  labels:
    description: 'Labels to add to the issues. You can specify multiple labels separated by newlines. Defaults to "sync". If empty string is provided, no labels will be added.'
    required: false
    default: |
      sync
  release-tracking:
    description: 'Whether to enable release tracking. When enabled, Ryu-Cho will track releases for each issue and add comments about release status.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout Ryu-Cho
      run: ${{ github.action_path }}/scripts/checkout.sh
      shell: bash
    - name: Run Ryu-Cho
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        USER_NAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        UPSTREAM_REPO: ${{ inputs.upstream-repo }}
        HEAD_REPO: ${{ inputs.head-repo }}
        HEAD_REPO_BRANCH: ${{ inputs.head-repo-branch }}
        TRACK_FROM: ${{ inputs.track-from }}
        PATH_STARTS_WITH: ${{ inputs.path-starts-with }}
        LABELS: ${{ inputs.labels }}
        RELEASE_TRACKING: ${{ inputs.release-tracking }}
      run: |
        cd ryu-cho
        yarn install
        yarn start
      shell: bash
