name: 'Yuki-no'
description: 'Automatic git commit tracking service.'

inputs:
  access-token:
    description: 'GitHub access token.'
    required: true
  username:
    description: 'Git user name to use when making issues and PRs. Defaults to "github-actions". Note: Using only one of username or email might cause GitHub Actions bot to work incorrectly.'
    required: false
    default: 'github-actions'
  email:
    description: 'Git email address to use when making issues and PRs. Defaults to "action@github.com". Note: Using only one of username or email might cause GitHub Actions bot to work incorrectly.'
    required: false
    default: 'action@github.com'
  upstream-repo:
    description: 'The url for the upstream repo. If not specified, the current repository will be used. e.g. https://github.com/vitejs/docs-ko.git'
    required: false
  head-repo:
    description: 'The head repo to track. This is the repository you want to take a diff. e.g. https://github.com/vitejs/vite.git'
    required: true
  head-repo-branch:
    description: 'The branch for the head repo. Defaults to "main".'
    required: false
    default: 'main'
  track-from:
    description: 'The git commit sha of head repo to start tracking. Yuki-no will only track commit from this hash.'
    required: true
  include:
    description: 'File patterns to include in tracking. Multiple patterns can be specified with newlines. Uses glob patterns. If not specified, all files will be tracked.'
    required: false
  exclude:
    description: 'File patterns to exclude from tracking. Multiple patterns can be specified with newlines. Uses glob patterns. Takes precedence over include patterns.'
    required: false
  labels:
    description: 'Labels to add to the issues. You can specify multiple labels separated by newlines. Defaults to "sync". If empty string is provided, no labels will be added.'
    required: false
    default: |
      sync
  release-tracking:
    description: 'Whether to enable release tracking. When enabled, Yuki-no will track releases for each issue and add comments about release status.'
    required: false
  release-tracking-labels:
    description: 'Labels to add to issues when release tracking is enabled. These labels will be added to issues that have not been released yet and removed when the changes are released. You can specify multiple labels separated by newlines. Defaults to "pending". If empty string is provided, no labels will be added. Any labels that overlap with the "labels" option will be filtered out.'
    required: false
    default: |
      pending
  verbose:
    description: 'Whether to enable verbose logging. When enabled, Yuki-no will show all log messages including info and success messages. This is useful for debugging.'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "YUKI_NO_VERSION=${action_ref}" >> $GITHUB_ENV
      env:
        action_ref: ${{ github.action_ref }}

    - name: Checkout Yuki-no
      run: ${{ github.action_path }}/scripts/checkout.sh
      shell: bash

    - name: Run Yuki-no
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        USER_NAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        UPSTREAM_REPO: ${{ inputs.upstream-repo }}
        HEAD_REPO: ${{ inputs.head-repo }}
        HEAD_REPO_BRANCH: ${{ inputs.head-repo-branch }}
        TRACK_FROM: ${{ inputs.track-from }}
        INCLUDE: ${{ inputs.include }}
        EXCLUDE: ${{ inputs.exclude }}
        LABELS: ${{ inputs.labels }}
        RELEASE_TRACKING: ${{ inputs.release-tracking }}
        RELEASE_TRACKING_LABELS: ${{ inputs.release-tracking-labels }}
        VERBOSE: ${{ inputs.verbose }}
      run: |
        cd yuki-no
        yarn install
        yarn start
      shell: bash
