name: 'Yuki-no'
description: 'GitHub Action for tracking upstream documentation changes'

inputs:
  access-token:
    description: 'Access token for GitHub authentication'
    required: true
  username:
    description: 'Username for authenticated user'
    required: true
  email:
    description: 'Email for authenticated user'
    required: true
  head-repo:
    description: 'Repository where issues will be created. e.g. https://github.com/vitejs/docs-ko.git'
    required: true
  upstream-repo:
    description: 'Source repository to track changes from. e.g. https://github.com/vitejs/vite.git'
    required: true
  upstream-repo-branch:
    description: 'Branch of the Source repository. Defaults to `main`'
    required: false
    default: 'main'
  path-starts-with:
    description: 'File path to track. e.g `docs/`'
    required: false
  initial-commit:
    description: 'The commit hash to start syncing from. Required to prevent syncing all historical commits.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Yuki-no
      run: ${{ github.action_path }}/scripts/checkout.sh
      shell: bash
    - name: Run Yuki-no
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        USER_NAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        UPSTREAM_REPO: ${{ inputs.upstream-repo }}
        UPSTREAM_REPO_BRANCH: ${{ inputs.upstream-repo-branch }}
        HEAD_REPO: ${{ inputs.head-repo }}
        PATH_STARTS_WITH: ${{ inputs.path-starts-with }}
        INITIAL_COMMIT: ${{ inputs.initial-commit }}
      run: |
        cd yuki-no
        yarn install
        yarn start
      shell: bash
