name: 'Yuki-no'
description: 'Automatic git commit tracking service.'

inputs:
  access-token:
    description: 'GitHub access token.'
    required: true
  username:
    description: 'Git username used for GitHub issue operations. Defaults to "github-actions".'
    required: false
    default: 'github-actions'
  email:
    description: 'Git username used for GitHub issue operations. Defaults to "action@github.com".'
    required: false
    default: 'action@github.com'
  upstream-repo:
    description: 'URL of your repository. If not specified, the current working repository will be used. e.g. https://github.com/vitejs/docs-ko.git'
    required: false
  head-repo:
    description: 'URL of repository to track. e.g. https://github.com/vitejs/vite.git'
    required: true
  head-repo-branch:
    description: 'Branch to track in head repo. Defaults to "main".'
    required: false
    default: 'main'
  track-from:
    description: 'Starting commit hash. Tracking starts from the next commit.'
    required: true
  include:
    description: 'Glob patterns for files to track. If not specified, all files will be tracked.'
    required: false
  exclude:
    description: 'Glob patterns for files to exclude. Take precedence over include patterns.'
    required: false
  plugins:
    description: 'Names of Yuki-no plugins to load with exact version specification (newline separated). Format: plugin-name@1.0.0 (exact version required).'
    required: false
  labels:
    description: 'Labels for issues. You can specify multiple labels separated by newlines. If empty string is provided, no labels will be added. Defaults to "sync".'
    required: false
    default: |
      sync
  release-tracking:
    description: '(Deprecated) Whether to enable release tracking. Use plugins: ["@yuki-no/plugin-release-tracking"] instead.'
    required: false
    deprecationMessage: 'release-tracking option is deprecated. Use plugins: ["@yuki-no/plugin-release-tracking"] instead. See documentation for migration guide.'
  release-tracking-labels:
    description: '(Deprecated) Labels for unreleased changes. Use env.YUKI_NO_RELEASE_TRACKING_LABELS instead.'
    required: false
    deprecationMessage: 'release-tracking-labels option is deprecated. Set YUKI_NO_RELEASE_TRACKING_LABELS in env block instead.'
    default: |
      pending
  verbose:
    description: 'When enabled, Yuki-no will show all log messages including info and success messages. This is useful for debugging.'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "YUKI_NO_VERSION=${action_ref}" >> $GITHUB_ENV
      env:
        action_ref: ${{ github.action_ref }}

    - name: Normalize plugins configuration
      shell: bash
      run: |
        if [ "${release_tracking}" = "true" ]; then
          echo "⚠️ Warning: RELEASE_TRACKING is deprecated..."

          NORMALIZED_PLUGINS="${plugins}"
          if [ ! -z "$NORMALIZED_PLUGINS" ]; then
            NORMALIZED_PLUGINS="$NORMALIZED_PLUGINS"$'\n'"@yuki-no/plugin-release-tracking@latest"
          else
            NORMALIZED_PLUGINS="@yuki-no/plugin-release-tracking@latest"
          fi
        else
          NORMALIZED_PLUGINS="${plugins}"
        fi

        echo "PLUGINS<<EOF" >> $GITHUB_ENV
        echo "$NORMALIZED_PLUGINS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        plugins: ${{ inputs.plugins }}
        release_tracking: ${{ inputs.release-tracking }}

    # Fix workspace package symlink issues when used as plugins
    # - Workspace packages get symlinked, but their dist directories don't exist
    #   because local packages aren't built, causing runtime failures
    # - node-linker=hoisted: Creates flat node_modules, eliminates .pnpm virtual store
    # - symlink=false: Prevents workspace package symlinks (overrides special workspace handling)
    # - package-import-method=hardlink: Forces hardlinks from global store (consistent across filesystems)
    - name: Configure pnpm to fix workspace package symlink issues
      shell: bash
      run: |
        echo "node-linker=hoisted" > .npmrc
        echo "symlink=false" >> .npmrc
        echo "package-import-method=hardlink" >> .npmrc

    - name: Checkout Yuki-no
      run: ${{ github.action_path }}/scripts/checkout.sh
      shell: bash

    - name: Run Yuki-no
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        USER_NAME: ${{ inputs.username }}
        EMAIL: ${{ inputs.email }}
        UPSTREAM_REPO: ${{ inputs.upstream-repo }}
        HEAD_REPO: ${{ inputs.head-repo }}
        HEAD_REPO_BRANCH: ${{ inputs.head-repo-branch }}
        TRACK_FROM: ${{ inputs.track-from }}
        INCLUDE: ${{ inputs.include }}
        EXCLUDE: ${{ inputs.exclude }}
        PLUGINS: ${{ env.PLUGINS }}
        LABELS: ${{ inputs.labels }}
        VERBOSE: ${{ inputs.verbose }}
        YUKI_NO_RELEASE_TRACKING_LABELS: ${{ inputs.release-tracking-labels }} # compat
      run: |
        cd yuki-no
        pnpm start
      shell: bash
