import { log } from '@yuki-no/plugin-sdk/utils/log';

export type BatchIssueType = 'Resolved';

type BatchIssueStatus = {
  number: number;
  type: BatchIssueType;
};

export const createPrBody = (
  issueStatus: BatchIssueStatus[],
  mismatchedFiles: string[] = [],
): string => {
  log('I', `createPrBody :: Creating PR body for ${issueStatus.length} issues`);

  const resolvedIssueComments = issueStatus.map(createIssueComment);
  const mismatchedFileComments = mismatchedFiles.map(createMismatchedFileComment);

  const mismatchedFilesSection =
    mismatchedFiles.length > 0
      ? mismatchedFileComments.join('\n')
      : 'All files were applied successfully.';

  return `
> [!CAUTION]
> **DO NOT EDIT THIS PR MANUALLY**
> This PR is automatically managed by the Batch PR plugin. Manual changes will be overwritten.

## ❄️ Batch Pull Request

This PR collects opened Yuki-no translation issues into a single pull request.

### Resolved Issues

${resolvedIssueComments.join('\n')}

### ⚠️ Files with Line Mismatches

The following files were not updated because the line count has changed since the patch was created. Please review them manually.

${mismatchedFilesSection}

---
*Generated by [Yuki-no Batch PR Plugin](https://github.com/Gumball12/yuki-no/tree/next/packages/batch-pr/)*
`;
};

const createIssueComment = (issueStatus: BatchIssueStatus): string =>
  `${issueStatus.type} #${issueStatus.number}`;

const createMismatchedFileComment = (fileName: string): string =>
  `- \`${fileName}\``;
