import { log } from '@yuki-no/plugin-sdk/utils/log';

export type BatchIssueType = 'Resolved';

type BatchIssueStatus = {
  number: number;
  type: BatchIssueType;
};

type PrBodyOptions = {
  excludedFiles?: string[];
};

// TODO: YUKI_NO_BATCH_PR_ROOT_DIR 이용해 여기 기준으로 excluded files 필터링 & 명시해야 함
// 안그럼 필요하지도 않은 애들까지 포함되어서 너무 길어지고 많아진다...
export const createPrBody = (
  issueStatus: BatchIssueStatus[],
  { excludedFiles } = {} as PrBodyOptions,
): string => {
  log('I', `createPrBody :: Creating PR body for ${issueStatus.length} issues`);

  const resolvedIssueComments = issueStatus.map(createIssueComment);
  const excludedFileComments = excludedFiles?.map(createExcludedFileComment);

  return `
> [!CAUTION]
> **DO NOT EDIT THIS PR MANUALLY**
> This PR is automatically managed by the Batch PR plugin. Manual changes will be overwritten.

## ❄️ Batch Pull Request

This PR collects opened Yuki-no translation issues into a single pull request.

### Resolved Issues

${resolvedIssueComments.join('\n')}

### Excluded Files (manual changes required)

> These files matched \`YUKI_NO_BATCH_PR_EXCLUDE\` and were not applied by the plugin. Please update them manually.

${excludedFileComments?.join('\n')}

---
*Generated by [Yuki-no Batch PR Plugin](https://github.com/Gumball12/yuki-no/tree/next/packages/batch-pr/)*
`;
};

const createIssueComment = (issueStatus: BatchIssueStatus): string =>
  `${issueStatus.type} #${issueStatus.number}`;

const createExcludedFileComment = (excludedFileName: string): string =>
  `- \`${excludedFileName}\``;
